import {
  Baby,
  Ban,
  Bed,
  BookOpen,
  Bike,
  Brain,
  Briefcase,
  Camera,
  Car,
  Cigarette,
  Circle,
  Clock,
  CloudRain,
  Coffee,
  Dog,
  Droplets,
  Dumbbell,
  Flame,
  Footprints,
  Gamepad2,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Laptop,
  Leaf,
  Moon,
  Music,
  Palette,
  Pencil,
  PiggyBank,
  Pill,
  Plane,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Sun,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Utensils,
  Wallet,
  Wine,
  type LucideIcon,
} from "lucide-react";

// A curated, safe set: specs (whether hand-edited or, later, AI-generated) can only pick
// an icon *id* from this list, never arbitrary code or markup.
export const ICONS: Record<string, LucideIcon> = {
  moon: Moon,
  sun: Sun,
  briefcase: Briefcase,
  dumbbell: Dumbbell,
  droplets: Droplets,
  wallet: Wallet,
  book: BookOpen,
  brain: Brain,
  heart: Heart,
  smile: Smile,
  coffee: Coffee,
  music: Music,
  palette: Palette,
  target: Target,
  users: Users,
  pencil: Pencil,
  sparkles: Sparkles,
  clock: Clock,
  utensils: Utensils,
  bike: Bike,
  ban: Ban,
  pill: Pill,
  circle: Circle,
  smartphone: Smartphone,
  laptop: Laptop,
  gamepad: Gamepad2,
  dog: Dog,
  baby: Baby,
  graduation: GraduationCap,
  car: Car,
  plane: Plane,
  home: Home,
  bed: Bed,
  cigarette: Cigarette,
  wine: Wine,
  gift: Gift,
  cart: ShoppingCart,
  piggy: PiggyBank,
  trending: TrendingUp,
  rain: CloudRain,
  flame: Flame,
  leaf: Leaf,
  camera: Camera,
  headphones: Headphones,
  footprints: Footprints,
  trophy: Trophy,
};

export const ICON_IDS = Object.keys(ICONS);
export const DEFAULT_ICON = "circle";
export const iconFor = (id: string): LucideIcon => ICONS[id] ?? ICONS[DEFAULT_ICON];
